LOCAL_PATH := $(/system/apps)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := gcam

LOCAL_CERTIFICATE := PRESIGNED

LOCAL_SRC_FILES := gcam.apk

LOCAL_MODULE_CLASS := APPS

LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)
